version: '3.8'

services:
  app:
    build: .
    container_name: NODE_REGIS
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - SQL_HOST=db           
      - SQL_USER=root
      - SQL_PASSWORD=admin
      - SQL_DATABASE=database_users 
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: database_users
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    ports:
      - "8081:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8082:80"
    depends_on:
      - db
